const products = [
  {
    _id: '2b7d926e-f145-4ef1-b686-be57f7112b0d',
    rating: 5,
    numReviews: 1,
    price: 799,
    countInStock: 1000,
    name: 'iPhone 12',
    image: '/images/iphone-12.png',
    brand: 'Apple',
    category: 'Phones',
    description:
      '5G. A14 Bionic. All‑new design. Ceramic Shield. Edge‑to‑edge OLED display. Night mode on every camera. All in two perfect sizes.',
    reviews: [],
  },
  {
    _id: '97ebfaf6-081c-49e2-aaa4-a39a2f843804',
    rating: 4.5,
    numReviews: 2,
    price: 1999,
    countInStock: 500,
    name: 'iMac 27-inch',
    image: '/images/imac.png',
    brand: 'Apple',
    category: 'Computers',
    description:
      'The all-in-one for all. If you can dream it, you can do it on iMac. It’s beautifully designed, incredibly intuitive, and packed with powerful tools that let you take any idea to the next level.',
    reviews: [],
  },
  {
    _id: 'e242f1eb-23d4-4b7c-aae1-279eb06650f2',
    rating: 4.3,
    numReviews: 10,
    price: 899,
    countInStock: 500,
    name: 'Samsung S20',
    image: '/images/samsung-s20.png',
    brand: 'Samsung',
    category: 'Phones',
    description:
      'Meet Galaxy S20. With revolutionary 8K Video Snap changing how you capture not just video but photography — and 5G changing the way you share it. Add in Samsung Knox security, an intelligent battery, powerful processor and massive storage — and the Galaxy S2 unveils a whole new world for mobile.',
    reviews: [],
  },
  {
    _id: 'baf6dcad-41b8-4354-b324-7a9fe2eb33ad',
    rating: 5,
    numReviews: 1,
    price: 1059.99,
    countInStock: 300,
    name: 'BenQ PD3220U',
    image: '/images/benq-PD3220U.png',
    brand: 'BenQ',
    category: 'Monitors',
    description:
      'Created with such demand in mind, BenQ’s PD3220U comes with an aesthetically elegant look that prioritizes flexibility and designers’ love for sophistication. To satisfy designers’ needs for impeccable color performances while enhancing the overall productivity for them.',
    reviews: [],
  },
  {
    _id: 'f197af3a-ff63-4981-8ad4-aaad4e34bf56',
    rating: 4,
    numReviews: 6,
    price: 349.99,
    countInStock: 450,
    name: 'Sony WH-1000XM4',
    image: '/images/sony-WH-1000XM4.png',
    brand: 'Sony',
    category: 'Headphones',
    description:
      'Whether you’re flying long-haul or relaxing in a café, the WH-1000XM4 headphones deliver our best ever noise cancelling performance, keeping out even more high and mid frequency sounds.',
    reviews: [],
  },
  {
    _id: 'd5fe4191-b605-4cc6-9dec-c8f8af1ec8a0',
    rating: 4.8,
    numReviews: 12,
    price: 249,
    countInStock: 800,
    name: 'AirPods Pro ',
    image: '/images/airpods-pro.png',
    brand: 'Apple',
    category: 'Headphones',
    description:
      'AirPods Pro have been designed to deliver Active Noise Cancellation for immersive sound, Transparency mode so you can hear your surroundings and a customizable fit for all-day comfort.',
    reviews: [],
  },
  {
    _id: 'ca515c58-0a7c-49c7-943b-a9b1b0212424',
    rating: 5,
    numReviews: 12,
    price: 429,
    countInStock: 350,
    name: 'Apple Watch',
    image: '/images/apple-watch.png',
    brand: 'Apple',
    category: 'Watches',
    description:
      'Measure your blood oxygen level with a revolutionary new sensor and app. Take an ECG anytime, anywhere. See your fitness metrics at a glance with the enhanced Always-On Retina display. With Apple Watch Series 6 on your wrist, a healthier, more active, more connected life is within reach.',
    reviews: [],
  },
  {
    _id: 'd95a5431-d9f1-4e68-8a59-51285cb7c549',
    rating: 3,
    numReviews: 3,
    price: 299.99,
    countInStock: 250,
    name: 'Astro A50',
    image: '/images/astro-a50.png',
    brand: 'Astro',
    category: 'Headphones',
    description:
      'Experience the performance and sound of ASTRO Audio V2 with the convenience and freedom that comes without wires. The A50 Wireless + Base Station for Xbox/PC, delivers top-of-the-line acoustics, ergonomics, comfort and durability that gamers and streamers demand. Experience Absolute Immersion with the A50 Wireless + Base Station.',
    reviews: [],
  },
]

export default products
