export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_USER_REQUEST = 'ORDER_USER_REQUEST'
export const ORDER_USER_SUCCESS = 'ORDER_USER_SUCCESS'
export const ORDER_USER_FAIL = 'ORDER_USER_FAIL'
export const ORDER_USER_RESET = 'ORDER_USER_RESET'

export const ORDER_ALL_USERS_REQUEST = 'ORDER_ALL_USERS_REQUEST'
export const ORDER_ALL_USERS_SUCCESS = 'ORDER_ALL_USERS_SUCCESS'
export const ORDER_ALL_USERS_FAIL = 'ORDER_ALL_USERS_FAIL'
export const ORDER_ALL_USERS_RESET = 'ORDER_ALL_USERS_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'
